///////////////////////////////////////////////////////////////////////////////
// Name:        Icon.inc
// Purpose:     Display the window About WxPic
// Author:      Philippe Chevrier
// Modified by:
// Created:     2009.06.01
// Copyright:   (c) 2009 Philippe Chevrier <pch@laposte.net>
// License:     GNU Lesser General Public License (LGPLv3)
///////////////////////////////////////////////////////////////////////////////

ICON_DEF(WxPic)
ICON_DEF(ChipRead)
ICON_DEF(ChipVerify)
ICON_DEF(ChipWrite)
ICON_DEF(ChipReload)
ICON_DEF(LedGreen)
ICON_DEF(LedRed)
ICON_DEF(LedOff)
ICON_DEF(Open)
ICON_DEF(Save)

