#ifndef VERSION_H_INCLUDED
#define VERSION_H_INCLUDED

#ifdef USE_SVN_VERSION
#include "../version.autogen"
//-- version.autogen is autogenerated from SVN information and status of the project directory at each build
//-- It is not itself in configuration management (it would have to know the version before it exists!)
#else
//-- Manual version definition
#define SVN_DATE     (wxT(""))
#define SVN_REVISION (0)
#define SVN_VERSION  (wxT(""))
#define SVN_MANAGED  (false)
#endif

#endif // VERSION_H_INCLUDED
